### PR TITLE
Don't use writeByteArray() in xposed_service.cpp

### PR DESCRIPTION
**Pull request by romracer**
I have a pretty detailed comment in romracer/Xposed@7081ac6.

Do you have any recollection of why you used writeByteArray() originally on LP?  It seems to work fine using writeInt32()/write().

Sorry for the commit history, I'll be rebasing my branches soon to clean a lot of that up.  Feel free to cherry-pick and close the pull request.

This fixes rovo89/XposedBridge#58.

### CODE REVIEW

**Comment by rsteckler** [comment]
I've tested this fix on a arm64 Nexus 9 with 5.1.1 and its working in my module for XSharedPreferences.

**Comment by rovo89** [comment]
Please give me a day or two to verify this. I used this method because it claims to do exactly what I want. Except that if you're right, AOSP is broken at this point. The alternative implementation for pre-Lollipop was added later when I tried to compile the same code for older releases.

Btw, I don't see the errors for the bug in my Nexus 9 logcat and App Settings can load its preferences. But maybe it still uses the ones it retrieved in Zygote and doesn't complain when it can't refresh.

**Comment by rovo89** [comment]
So the root cause seems to be a bug in AOSP, introduced by this commit: https://android.googlesource.com/platform/frameworks/native/+/f0190bff38b6c29abbfc4a877442f71fc3d7dad8

As you said, it uses size_t when it should used uint32_t for the length of the array. This bug still exists in the master branch: https://android.googlesource.com/platform/frameworks/native/+/master/libs/binder/Parcel.cpp
Not sure if it's worth to send a patch for this bug to Google.

I'll try to reproduce the original bug as soon as possible and then verify that this change fixes it.

**Comment by arter97** [comment]
@romracer, this pull-request brings your 5.1 changes too(which it seems rovo89 have fixed himself), which might not look all that good on Git history. The only commit relevant to this issue seems to be 7081ac6.

**Comment by romracer** [comment]
Right, which is why I suggested the cherry-pick.  I'm sure @rovo89's knows what he's doing, he's done it before :)

As for this bug, I'm not sure its a bug in AOSP necessarily.  When the service proxy reads the data returned from the server, it assumes a 32-bit integer for the number of bytes read [here](https://github.com/rovo89/Xposed/blob/master/xposed_service.cpp#L497).

However, [writeByteArray()](https://github.com/rovo89/Xposed/blob/master/xposed_service.cpp#L585) on the server side can potentially write a 64-bit integer in that position (a padded 32-bit integer since that's all we pass).  So when the service proxy next reads [here](https://github.com/rovo89/Xposed/blob/master/xposed_service.cpp#L506), the first 32-bits of that data are actually the padding from the "bytes read" integer.

Since bytesRead is int32_t, I don't know why we wouldn't just use writeInt32()/write().  Internally, its the same code as best I can tell.

**Comment by rovo89** [comment]
I say this is an AOSP bug because I expect a method called "writeByteArray" to do exactly that. I expect that I can read the byte array from the Java side, which uses JNI to call these methods:
[writeNative](https://github.com/android/platform_frameworks_base/blob/android-5.1.1_r13/core/jni/android_os_Parcel.cpp#L163)
[createByteArray](https://github.com/android/platform_frameworks_base/blob/android-5.1.1_r13/core/jni/android_os_Parcel.cpp#L313)
As you can see, both of them use 32-bit integers to read the size. Either the native Parcel::writeByteArray isn't meant as a counter-part for that, or it's an AOSP bug (or I might be missing something).

**Comment by rovo89** [comment]
Currently, Parcel::writeByteArray isn't used anymore, I guess that's why it wasn't noticed. The bug number revealed that this was introduced in 4.4.x for this usage: https://android.googlesource.com/platform/frameworks/av/+/8a57d24c733b08da846b54d1adf029e606b5a5f3
There was no 64-bit support for KitKat, so this never was a problem.

**Comment by rovo89** [comment]
Alright, I cherry-picked your change (with a changed message though) and published v73. Thanks to both of you!

**Comment by rsteckler** [comment]
Pretty awesome that we found a bug in the AOSP code.  Thanks both for the help.

**Pull request closed without merging**
